dubbo:
  application:
    name: microservice-producer
  monitor:
    protocol: registry
  protocol:
    name: dubbo
    port: 28081
  registry:
    address: zookeeper://uaian.top:2181
    id: dubbo-registry
server:
  port: 8084
